#!/bin/sh
# D2 drift guard: modules/blocker/ is the single native source; android/ is
# regenerated by `expo prebuild` (modules/blocker/plugin.js). Run after any
# native change: `npm run check:native-mirror`. Fails loudly on drift.
set -e
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
diff -rq "$ROOT/modules/blocker/src/main/java/com/nitridee/staytapp/blocker" "$ROOT/android/app/src/main/java/com/nitridee/staytapp/blocker"
diff -rq "$ROOT/modules/blocker/src/main/res/xml" "$ROOT/android/app/src/main/res/xml"
for s in accessibility_service_description stayt_widget_desc; do
  grep -q "name=\"$s\"" "$ROOT/android/app/src/main/res/values/strings.xml" || { echo "missing string: $s"; exit 1; }
done
echo "native mirror OK"
